<?php
/**
 * Custom designed select element. Markup is generated by PHP but interactivity
 * is managed using javscript. 
 * 
 * TODO move Dropdown and Selct tag into a elements sub folder of the page builder
 */
class SelectTag extends Dropdown
{
	/**
	 * @param string $toggle_text Inital text 
	 * @param array $tag_id_list List of WP tag IDs (integers) to build the select list from
	 * @param string $callback Javascript function to call on select
	 */
    public function __construct(string $toggle_text, array $tag_id_list, string $callback = '')
    {
		parent::__construct($toggle_text, $callback);

		echo "<div class='pb_select pb_selecttag'>";

        foreach ($tag_id_list as $id) {
			//Find the human readable name
			if (is_int($id)) {
				$label = get_tag($id)->name;
			} else {
				$label = $id; 
			}
			echo "<input tabindex='-1' type='radio' id='$id' name='$callback' value='$label'>";
			echo "<label for='$id'>$label</label>";
		}
		
		echo '</div>';

		$this->close(); 
    }
}
